### ISSUE TITLE
Player: Application not Responding

### ISSUE THREAD

**Issue by JanzenJohn** [vinegarhq/vinegar#359] opened 2024-02-11 19:00 UTC
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).

When ever I launch the Player, it freezes after a couple seconds, and pins 4 CPU cores

#### To Reproduce
Launch the Player
Resize the Window or wait

### Logs
[Player-2024-02-11T19:56:53+01:00.log](https://github.com/vinegarhq/vinegar/files/14233661/Player-2024-02-11T19.56.53%2B01.00.log)

### System information
* Vinegar: v1.6.1 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 9 5900X 12-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.4-arch1-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:06:00.0 /sys/class/drm/card0

###Additional Info
After running some time more I get pinned 4 Pinned CPU Cores

**Comment by apprehensions** [comment] 2024-02-11 19:14
Duplicate of https://github.com/vinegarhq/vinegar/issues/224

**Closed** 2024-02-13 09:13 UTC
Labels: bug
