### ISSUE TITLE
roblox encountered an unexpected error

### ISSUE THREAD

**Issue by FantasyPvP** [vinegarhq/vinegar#271] opened 2023-11-16 00:01 UTC
#### Describe the bug
instantly crashes "roblox encountered an unexpected error"

#### To Reproduce
run the vinegar player command on arch after installing through AUR

### Logs
   1   │ 2023/11/15 23:55:47 version.go:45: Fetching latest version of WindowsPlayer for channel live
   2   │ 2023/11/15 23:55:47 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
   3   │ 2023/11/15 23:55:48 version.go:52: Fetched WindowsPlayer canonical version 0.603.0.6030563
   4   │ 2023/11/15 23:55:48 version.go:31: Got WindowsPlayer version version-8390cf89d2c74e62 with channel live
   5   │ 2023/11/15 23:55:48 binary.go:241: WindowsPlayer is up to date (version-8390cf89d2c74e62)
   6   │ 2023/11/15 23:55:48 fflags.go:30: Applying custom FFlags
   7   │ 2023/11/15 23:55:48 dxvk.go:20: Enabling WINE DXVK DLL overrides
   8   │ 2023/11/15 23:55:48 discordrpc.go:16: Authenticating Discord RPC
   9   │ 2023/11/15 23:55:48 binary.go:122: Launching WindowsPlayer
  10   │ 2023/11/15 23:55:48 cmd.go:74: Starting command: /usr/bin/wine /home/fantasypvp/.local/share/vinegar/prefix/vinegar/versions/version-8390cf8
       │ 9d2c74e62/RobloxPlayerBeta.exe
  11   │ 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  12   │ 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  13   │ 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  14   │ 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  15   │ 007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
  16   │ 007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
  17   │ 00d4:fixme:ntdll:NtRaiseHardError c0000005 stub
  18   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  19   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  20   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  21   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  22   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  23   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  24   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  25   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  26   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  27   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  28   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  29   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  30   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  31   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  32   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  33   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  34   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  35   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  36   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  37   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  38   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  39   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  40   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  41   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  42   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  43   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  44   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  45   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  46   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  47   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  48   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  49   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  50   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  51   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  52   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  53   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  54   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  55   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  56   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  57   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  58   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  59   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  60   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  61   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  62   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  63   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  64   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  65   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  66   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  67   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  68   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  69   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  70   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  71   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  72   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  73   │ 00d4:fixme:dbghelp:elf_search_auxv can't find symbol in module
  74   │ 2023/11/15 23:56:05 prefix.go:34: Killing wineprefix
  75   │ 2023/11/15 23:56:05 cmd.go:74: Starting command: /usr/bin/wineserver -k
  76   │ 2023/11/15 23:56:05 discordrpc.go:21: Deauthenticating Discord RPC

### System information
arch linux amd64, xorg window manager, kernel 6.6.1 amd graphics card with mesa drivers, KDE plasma desktop

* Installation method:
installed through AUR using paru and ran command: "vinegar player"

#### Additional context
I get the exact same error trying to run the app with grapejuice (a similar solution for running roblox through wine)

**Comment by apprehensions** [comment] 2023-11-16 05:51
Use Wine-GE or Use the Flatpak. 

Duplicate of #199

**Closed by apprehensions** 2023-11-16 05:51 UTC
Labels: bug
