### ISSUE TITLE
Exit status 1 after crash/kill

### ISSUE THREAD

**Issue by i3vie** [vinegarhq/vinegar#449] opened 2024-10-20 18:55 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Using Vinegar for Roblox Studio, Studio will launch fine, and generally works fine. However, if something causes it to crash/lock up and I have to manually kill it with xkill, I have to restart my computer before being able to launch Studio again. This can be fixed with a `killall -9 wineserver` but this may kill other processes running in any wine instance, and it might be a good idea to have a way for Vinegar to detect and fix this?

Logs when using `flatpak run org.vinegarhq.Vinegar studio run`:
```
Oct 20 13:52:47.774 INF Logging to file path=/home/i3vie/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Studio-2024-10-20T13:52:47-05:00.log
Oct 20 13:52:47.800 INF Fetching Binary Deployment name=WindowsStudio64 channel=""
Oct 20 13:52:48.055 INF Fetched Binary Deployment! name=WindowsStudio64 channel="" guid=version-2220a78ed1774256 version=0.647.0.6470717
Oct 20 13:52:48.056 INF Binary is up to date! name=WindowsStudio64 guid=version-2220a78ed1774256
Oct 20 13:52:48.056 INF Enabling WINE DXVK DLL overrides
Oct 20 13:52:48.056 INF DXVK up to date! version=2.3
Oct 20 13:52:48.057 INF Running Binary name=WindowsStudio64 cmd="/app/bin/wine64 /home/i3vie/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-2220a78ed1774256/RobloxStudioBeta.exe"
0410:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
Oct 20 13:52:48.070 ERR failed to run roblox: exit status 1
```

Output of `flatpak run org.vinegarhq.Vinegar sysinfo`:
```
* Vinegar: v1.7.7 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.11.4-zen1-1-zen
* Wine (Player): wine-9.18 (Staging)
* Wine (Studio): wine-9.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
  * Card 1: amdgpu 0000:03:00.0 /sys/class/drm/card2
```

System is Arch Linux, everything is updated to latest

**Comment by apprehensions** [comment] 2024-10-20 20:00
Duplicate of #428

**Closed by apprehensions** 2024-10-20 20:00 UTC
Labels: bug
