### ISSUE TITLE
Cant login.

### ISSUE THREAD

**Issue by h14turkiye** [vinegarhq/vinegar#176] opened 2023-09-28 14:21 UTC
After typing my credentials and pressing Log In button. A white window appears, what I presume is roblox bot detect.
![image](https://github.com/vinegarhq/vinegar/assets/112547995/7ff26131-5c9e-4b76-b277-43cbbaa93cc9)

**Comment by apprehensions** [comment] 2023-09-28 14:22
Please use Quick login, WebView is broken.

**Comment by apprehensions** [comment] 2023-09-28 14:23
Duplicate of #32

**Closed by apprehensions** 2023-09-28 14:22 UTC
