### ISSUE TITLE
HiDPI support?

### ISSUE THREAD

**Issue by cooldudeseven7Dev** [vinegarhq/vinegar#334] opened 2024-01-15 03:56 UTC
#### Describe the bug
I have a 2736x1824 display. WINE has very small. Normally, you use "winecfg". But, i cant launch that. How do I configure the DPI, like normal?

#### To Reproduce
Get HIDPI display. Run any wine app, or any vinegar app (studio, roblox app)/

#### Details:
I do meet the system requirements.
Installed by "Flatpak."

Distro: Arch

#### See the image below to see the error.
![image](https://github.com/vinegarhq/vinegar/assets/100153927/1ff3c046-b8c5-4907-bbc4-175f7c135575)

**Comment by apprehensions** [comment] 2024-01-15 04:41
Duplicate of #213

Additionally, provide some logs as to why winecfg fails to run..

**Closed by apprehensions** 2024-01-15 04:41 UTC
Labels: bug

**Comment by cooldudeseven7Dev** [comment] 2024-01-16 05:09
Ah yes, Sorry. I dont have WINE installed, But vinegar still runs. I installed it from flatpak. Therefore, You cant run winecfg.

**Comment by lunarlettuce** [comment] 2024-01-16 05:17
You will not be able to change DPI without causing Roblox Studio to crash. This is not a bug we can fix.

**Comment by cooldudeseven7Dev** [comment] 2024-01-16 07:00
Alright. Got it. Thanks.
