### ISSUE TITLE
Roblox studio wont work

### ISSUE THREAD

**Issue by Supervisor360** [vinegarhq/vinegar#79] opened 2023-08-24 17:29 UTC
When ever i try to boot it just shows the roblox studio loading screen and a error saying it stopped working then it gives me this error message

Thread ID=01bc renamed using MSVC extension (name=="CrashRep")
Thread ID=01c0 renamed using MSVC extension (name=="CrashRep")
Thread ID=01c4 renamed using MSVC extension (name=="ErrorUpl")
Thread ID=01c8 renamed using MSVC extension (name=="Deferred")
Thread ID=01cc renamed using MSVC extension (name=="HttpThre")
Thread ID=01e8 renamed using MSVC extension (name=="PluginLo")
Thread ID=01ec renamed using MSVC extension (name=="PluginLo")
Thread ID=01e4 renamed using MSVC extension (name=="PluginLo")
Thread ID=01f4 renamed using MSVC extension (name=="PluginLo")
Thread ID=01f0 renamed using MSVC extension (name=="PluginLo")
Thread ID=01fc renamed using MSVC extension (name=="PluginLo")
Thread ID=01f8 renamed using MSVC extension (name=="PluginLo")
Thread ID=0200 renamed using MSVC extension (name=="PluginLo")
Thread ID=0204 renamed using MSVC extension (name=="EventIng")
Unhandled exception: page fault on read access to 0xffffffffffffffff in 64-bit code (0x000000015af829).
Register dump:
 rip:00000000015af829 rsp:00000000001170f0 rbp:0000000024410062 eflags:00010246 (  R- --  I  Z- -P- )
 rax:00000000ffffffff rbx:0000000000117188 rcx:0000000000117188 rdx:e404ff0471af3b74
 rsi:000000000faf1f80 rdi:000000000faf5870  r8:0000000000000000  r9:0000000000000000 r10:0000000000000000
 r11:0000000000000000 r12:00000000ffffffff r13:000000000faf2068 r14:0000000000000000 r15:0000000000117380
Stack dump:
0x000000001170f0:  ffffffffffe58000 0000000024410062
0x00000000117100:  000000000faf1f80 00000002c73ad0f6
0x00000000117110:  0000000001a324f8 0000000000000000
0x00000000117120:  00000000001171d8 00000000014f500b
0x00000000117130:  0000000000117380 00000002bb0c779c
0x00000000117140:  000000000faf1f80 00000000ffffffff
0x00000000117150:  0000000000000000 0000000000000000
0x00000000117160:  0000000000000000 00000000057d1d19
0x00000000117170:  00000000ffffffff 0000000024410062
0x00000000117180:  0000000001a324f8 000000000faf2110
0x00000000117190:  0000000000000000 00000002bb0c719c
0x000000001171a0:  000000000faf1f80 0000000000000000
Backtrace:
=>0 0x000000015af829 in qt5core (+0xbf829) (0x00000024410062)
  1 0x000000014f500b in qt5core (+0x500b) (0x00000024410062)
  2 0x000000057d1d19 in qwindows (+0x71d19) (0x00000024410062)
  3 0x000000057cfd86 in qwindows (+0x6fd86) (0x00000000117269)
  4 0x000000057c72ee in qwindows (+0x672ee) (0x000000001173d0)
  5 0x000000057c9078 in qwindows (+0x69078) (0000000000000000)
  6 0x00000000f4e2fa in qt5gui (+0xee2fa) (0x00000000117659)
  7 0x00000000f4deee in qt5gui (+0xedeee) (0x00000000117850)
  8 0x00000000f4a881 in qt5gui (+0xea881) (0x00000000117850)
  9 0x00000000f3a75b in qt5gui (+0xda75b) (0x00000000117a98)
  10 0x00000000f38ff8 in qt5gui (+0xd8ff8) (0x00000000117b79)
  11 0x00000000f3c409 in qt5gui (+0xdc409) (0x00000000117b79)
  12 0x00000000f5fe81 in qt5gui (+0xffe81) (0x00000000117cd0)
  13 0x00000000f5f759 in qt5gui (+0xff759) (0000000000000000)
  14 0x00000000f67ff3 in qt5gui (+0x107ff3) (0x00000000117f30)
  15 0x00000000f6a3ca in qt5gui (+0x10a3ca) (0x000000001182a0)
  16 0x00000000fa3df8 in qt5gui (+0x143df8) (0x000000001182a0)
  17 0x00000000fa62fb in qt5gui (+0x1462fb) (0x00000000118530)
  18 0x00000000fa7255 in qt5gui (+0x147255) (0x00000000118ac0)
  19 0x00000000fa7969 in qt5gui (+0x147969) (0x0000000fa92070)
  20 0x00000000fa06e9 in qt5gui (+0x1406e9) (0x0000000f8f36f0)
  21 0x00000000f9af1f in qt5gui (+0x13af1f) (0x00000000118d89)
  22 0x00000000f885c8 in qt5gui (+0x1285c8) (0x00000000118e60)
  23 0x00000000f83efa in qt5gui (+0x123efa) (0000000000000000)
  24 0x00000000a2f472 in qt5widgets (+0x11f472) (0x0000000f75e7a0)
  25 0x00000000a2f2bb in qt5widgets (+0x11f2bb) (0x000000001190c0)
  26 0x00000000a316a4 in qt5widgets (+0x1216a4) (0x000000001190c0)
  27 0x00000000a2fbac in qt5widgets (+0x11fbac) (0x0000000f968640)
  28 0x00000000a31a84 in qt5widgets (+0x121a84) (0x00000000119239)
  29 0x0000000093e4bb in qt5widgets (+0x2e4bb) (0x00000000119239)
  30 0x0000000093dcc6 in qt5widgets (+0x2dcc6) (0x000000001193d0)
  31 0x00000000933587 in qt5widgets (+0x23587) (0x000000001193d0)
  32 0x00000000932c8d in qt5widgets (+0x22c8d) (0x000000001194f0)
  33 0x0000000093a0dd in qt5widgets (+0x2a0dd) (0000000000000000)
  34 0x00000000939100 in qt5widgets (+0x29100) (0000000000000000)
  35 0x00000000957f9e in qt5widgets (+0x47f9e) (0x0000000f928b30)
  36 0x00000000957e5e in qt5widgets (+0x47e5e) (0x000000001197c0)
  37 0x00000000784ce3 in qtitandocking (+0x34ce3) (0x000000001197c0)
  38 0x00000140d1e378 in robloxstudiobeta (+0xd1e378) (0x000000001197c0)
  39 0x00000140d22bcc in robloxstudiobeta (+0xd22bcc) (0x00000007c93b40)
  40 0x00000140e3a3ca in robloxstudiobeta (+0xe3a3ca) (0x00000007c93b40)
  41 0x00000140e428c5 in robloxstudiobeta (+0xe428c5) (0x00000007c93b40)
  42 0x00000140e3f033 in robloxstudiobeta (+0xe3f033) (0x0000000011a600)
  43 0x00000140e3d4ae in robloxstudiobeta (+0xe3d4ae) (0x0000000011a600)
  44 0x00000140e3f5f2 in robloxstudiobeta (+0xe3f5f2) (0x0000000011a770)
  45 0x000001405004fb in robloxstudiobeta (+0x5004fb) (0x0000000011a770)
  46 0x000001404ff749 in robloxstudiobeta (+0x4ff749) (0000000000000000)
  47 0x00000140500a1f in robloxstudiobeta (+0x500a1f) (0x0000000011ad29)
  48 0x000001404e1ce2 in robloxstudiobeta (+0x4e1ce2) (0x0000000011adf0)
  49 0x000001404e7c47 in robloxstudiobeta (+0x4e7c47) (0x0000000011af20)
  50 0x000000016ebc94 in qt5core (+0x1fbc94) (0x0000000011b1a0)
  51 0x000000016ea631 in qt5core (+0x1fa631) (0x0000000011b1a0)
  52 0x00000000924951 in qt5widgets (+0x14951) (0x000000049e9160)
  53 0x000000009239d3 in qt5widgets (+0x139d3) (0x0000000011b3e0)
  54 0x00000140ba66fb in robloxstudiobeta (+0xba66fb) (0x00000005452ef0)
  55 0x000000016c356b in qt5core (+0x1d356b) (0x00000005452ef0)
  56 0x000000016c52f5 in qt5core (+0x1d52f5) (0x0000000011b9b0)
  57 0x000000057c3d4f in qwindows (+0x63d4f) (0x0000000011bb20)
  58 0x0000000170c6c4 in qt5core (+0x21c6c4) (0x0000000011bb20)
  59 0x000000057c3d29 in qwindows (+0x63d29) (0x0000000011ec00)
  60 0x000000016bf9bf in qt5core (+0x1cf9bf) (0x0000000011ec00)
  61 0x000000016c2535 in qt5core (+0x1d2535) (0000000000000000)
  62 0x000001404ed964 in robloxstudiobeta (+0x4ed964) (0000000000000000)
  63 0x0000014378f517 in robloxstudiobeta (+0x378f517) (0000000000000000)
  64 0x000001435927c6 in robloxstudiobeta (+0x35927c6) (0000000000000000)
  65 0x0000007b629f59 in kernel32 (+0x29f59) (0000000000000000)
  66 0x00000170062363 in ntdll (+0x62363) (0000000000000000)
0x000000015af829 qt5core+0xbf829: cmp %r8w, (%rdx)
Modules:
Module	Address					Debug info	Name (167 modules)
PE	0000000000750000-00000000007e1000	Export          qtitandocking
PE	00000000007f0000-000000000090e000	Deferred        qtitanbase
PE	0000000000910000-0000000000e5c000	Export          qt5widgets
PE	0000000000e60000-00000000014ea000	Export          qt5gui
PE	00000000014f0000-0000000001acf000	Export          qt5core
PE	0000000001ad0000-0000000001b08000	Deferred        qt5xml
PE	0000000001b10000-0000000001b3f000	Deferred        webview2loader
PE	0000000001b40000-0000000001f42000	Deferred        qt5quick
PE	0000000001f50000-0000000001fbf000	Deferred        qt5qmlmodels
PE	0000000001fc0000-0000000002338000	Deferred        qt5qml
PE	0000000002340000-000000000244a000	Deferred        qt5network
PE	0000000002450000-0000000002770000	Deferred        qtitanribbon
PE	0000000002770000-0000000002843000	Deferred        crypt32
PE	0000000002850000-0000000002956000	Deferred        sgcore
PE	0000000005760000-00000000058cf000	Export          qwindows
PE	00000000058d0000-00000000058f6000	Deferred        qwindowsvistastyle
PE	0000000005900000-000000000590d000	Deferred        qgif
PE	0000000005910000-0000000005982000	Deferred        qjpeg
PE	000000000dbc0000-000000000dbca000	Deferred        libegl
PE	0000000012440000-000000001277c000	Deferred        libglesv2
PE	00000000131c0000-00000000131ca000	Deferred        qtquick2plugin
PE	00000000131d0000-00000000131e1000	Deferred        qt5qmlworkerscript
PE	00000000131f0000-0000000013245000	Deferred        qtquickcontrolsplugin
PE	0000000013250000-0000000013264000	Deferred        qtgraphicaleffectsplugin
PE	000000007a800000-000000007a909000	Deferred        opengl32
PE	000000007b000000-000000007b29f000	Deferred        kernelbase
PE	000000007b600000-000000007b65f000	Export          kernel32
ELF	000000007d000000-000000007d005000	Deferred        <wine-loader>
PE	0000000140000000-000000014799f000	Export          robloxstudiobeta
PE	0000000170000000-00000001700a8000	Export          ntdll
PE	0000000180000000-00000001809c2000	Deferred        libfbxsdk
PE	00000001cb930000-00000001cb977000	Deferred        dxgi
PE	00000001ccdd0000-00000001cce02000	Deferred        rsaenh
PE	00000001cd620000-00000001cd632000	Deferred        aclui
PE	00000001ce760000-00000001ce76e000	Deferred        kerberos
PE	00000001d0e20000-00000001d0f5e000	Deferred        oleaut32
PE	00000001d3e90000-00000001d3e9c000	Deferred        msvcp140_1
PE	00000001d4930000-00000001d4958000	Deferred        netapi32
PE	00000001d8c90000-00000001d8cd3000	Deferred        advapi32
PE	00000001dbc50000-00000001dbccb000	Deferred        dwrite
PE	00000001eaf60000-00000001eaf8a000	Deferred        sechost
PE	00000001ffb10000-00000001ffb22000	Deferred        rtworkq
PE	000000020b860000-000000020b981000	Deferred        ole32
PE	00000002169d0000-0000000216b7d000	Deferred        user32
PE	0000000218320000-000000021834a000	Deferred        msdmo
PE	0000000228280000-000000022831b000	Deferred        msvcrt
PE	000000023bc00000-000000023c54f000	Deferred        shell32
PE	000000023ecb0000-000000023ed25000	Deferred        dbghelp
PE	0000000244fc0000-0000000244fce000	Deferred        userenv
PE	0000000250cd0000-0000000250cef000	Deferred        mpr
PE	0000000251d80000-0000000251db2000	Deferred        winex11
PE	000000025dc30000-000000025dc3e000	Deferred        version
PE	00000002605d0000-00000002605dc000	Deferred        vcruntime140
PE	0000000263650000-0000000263684000	Deferred        propsys
PE	000000026c190000-000000026c19c000	Deferred        nsi
PE	000000026c230000-000000026c266000	Deferred        uxtheme
PE	000000027a8e0000-000000027a915000	Deferred        d3d9
PE	0000000284ea0000-0000000284ead000	Deferred        powrprof
PE	00000002945e0000-00000002946a4000	Deferred        winmm
PE	0000000296590000-00000002965a7000	Deferred        dnsapi
PE	00000002a2380000-00000002a23dc000	Deferred        shlwapi
PE	00000002ac810000-00000002ac81e000	Deferred        vcruntime140_1
PE	00000002bb0a0000-00000002bb121000	Deferred        gdi32
PE	00000002bde30000-00000002bde4b000	Deferred        shcore
PE	00000002c73a0000-00000002c73d9000	Deferred        win32u
PE	00000002c7470000-00000002c7536000	Deferred        ucrtbase
PE	00000002d17d0000-00000002d17dd000	Deferred        mswsock
PE	00000002ee630000-00000002ee647000	Deferred        bcrypt
PE	00000002ef230000-00000002ef23e000	Deferred        dwmapi
PE	00000002fb3c0000-00000002fb50c000	Deferred        comctl32
PE	00000002fba30000-00000002fba56000	Deferred        concrt140
PE	000000030b860000-000000030b8d0000	Deferred        d3d11
PE	000000031bef0000-000000031bfd0000	Deferred        msvcp140
PE	000000031c5d0000-000000031c62d000	Deferred        combase
PE	000000032b540000-000000032b553000	Deferred        wintab32
PE	0000000345640000-00000003456c3000	Deferred        wininet
PE	0000000351a60000-0000000351a80000	Deferred        msacm32
PE	0000000367600000-0000000367869000	Deferred        wined3d
PE	0000000368420000-00000003684ab000	Deferred        rpcrt4
PE	000000036d860000-000000036d8e0000	Deferred        setupapi
PE	0000000370f70000-0000000370f98000	Deferred        ws2_32
PE	0000000393730000-000000039374c000	Deferred        imm32
PE	0000000394ba0000-0000000394bae000	Deferred        wtsapi32
PE	00000003982d0000-0000000398307000	Deferred        iphlpapi
PE	00000003afef0000-00000003aff11000	Deferred        secur32
PE	00000003bb450000-00000003bb4b6000	Deferred        mfplat
ELF	00007efbdf400000-00007efbe3f1d000	Deferred        libllvm-15.so
ELF	00007efbede00000-00007efbefcd3000	Deferred        iris_dri.so
ELF	00007efbeffdd000-00007efbf0000000	Deferred        libnss_resolve.so.2
ELF	00007efc1c1b9000-00007efc1c1f9000	Deferred        libtinfo.so.6
ELF	00007efc1cc04000-00007efc1cc0a000	Deferred        dwrite.so
ELF	00007efc1cd4e000-00007efc1cd5a000	Deferred        libpciaccess.so.0
ELF	00007efc1cd5a000-00007efc1cd80000	Deferred        libdrm_intel.so.1
ELF	00007efc1cd80000-00007efc1cd8d000	Deferred        libdrm_amdgpu.so.1
ELF	00007efc1cd8d000-00007efc1cda9000	Deferred        libelf.so.1
ELF	00007efc1cda9000-00007efc1cdb7000	Deferred        libdrm_radeon.so.1
ELF	00007efc1cdb7000-00007efc1cdc2000	Deferred        libdrm_nouveau.so.2
ELF	00007efc1cdc2000-00007efc1ce85000	Deferred        libzstd.so.1
ELF	00007efc1ce85000-00007efc1ce90000	Deferred        libxcb-xfixes.so.0
ELF	00007efc1ce90000-00007efc1ce9a000	Deferred        libxcb-sync.so.1
ELF	00007efc1ce9a000-00007efc1ce9f000	Deferred        libxcb-present.so.0
ELF	00007efc1ce9f000-00007efc1cea6000	Deferred        libxcb-dri3.so.0
ELF	00007efc1cea6000-00007efc1ceba000	Deferred        libxcb-randr.so.0
ELF	00007efc1ceba000-00007efc1cebf000	Deferred        libxshmfence.so.1
ELF	00007efc1cebf000-00007efc1cedd000	Deferred        libxcb-glx.so.0
ELF	00007efc1cedd000-00007efc1cf18000	Deferred        libglapi.so.0
ELF	00007efc1cf18000-00007efc1cf31000	Deferred        libdrm.so.2
ELF	00007efc1cf31000-00007efc1cf36000	Deferred        librt.so.1
ELF	00007efc1cf39000-00007efc1cf3e000	Deferred        libxcb-shm.so.0
ELF	00007efc1cf3e000-00007efc1cf45000	Deferred        libxcb-dri2.so.0
ELF	00007efc1cf45000-00007efc1cfb8000	Deferred        libglx_mesa.so.0
ELF	00007efc1cfb8000-00007efc1d071000	Deferred        libgldispatch.so.0
ELF	00007efc1d071000-00007efc1d0a4000	Deferred        libglx.so.0
ELF	00007efc1d0a4000-00007efc1d132000	Deferred        libgl.so.1
ELF	00007efc1d132000-00007efc1d1ad000	Deferred        libvulkan.so.1
ELF	00007efc1d1cd000-00007efc1d1dd000	Deferred        libffi.so.8
ELF	00007efc1d1dd000-00007efc1d25b000	Deferred        libgmp.so.10
ELF	00007efc1d25b000-00007efc1d2a6000	Deferred        libhogweed.so.6
ELF	00007efc1d2a6000-00007efc1d2f7000	Deferred        libnettle.so.8
ELF	00007efc1d2f7000-00007efc1d30d000	Deferred        libtasn1.so.6
ELF	00007efc1d30d000-00007efc1d4c6000	Deferred        libunistring.so.2
ELF	00007efc1d4c6000-00007efc1d600000	Deferred        libp11-kit.so.0
ELF	00007efc1d600000-00007efc1d81d000	Deferred        libgnutls.so.30
ELF	00007efc1d81e000-00007efc1d823000	Deferred        libx11-xcb.so.1
ELF	00007efc1d823000-00007efc1d82a000	Deferred        crypt32.so
ELF	00007efc1d82a000-00007efc1d87e000	Deferred        libidn2.so.0
ELF	00007efc1d882000-00007efc1d88e000	Deferred        bcrypt.so
ELF	00007efc1d88e000-00007efc1d89a000	Deferred        secur32.so
ELF	00007efc1d89a000-00007efc1d8ae000	Deferred        libresolv.so.2
ELF	00007efc1d8b2000-00007efc1d8b7000	Deferred        kerberos.so
ELF	00007efc1d8b7000-00007efc1d8be000	Deferred        netapi32.so
ELF	00007efc1d8e2000-00007efc1d8ea000	Deferred        libxfixes.so.3
ELF	00007efc1d8ee000-00007efc1d8f5000	Deferred        ws2_32.so
ELF	00007efc1d8f5000-00007efc1d8fa000	Deferred        dnsapi.so
ELF	00007efc1d8fa000-00007efc1d90e000	Deferred        libxi.so.6
ELF	00007efc1d90e000-00007efc1d913000	Deferred        libxcomposite.so.1
ELF	00007efc1d913000-00007efc1d920000	Deferred        libxrandr.so.2
ELF	00007efc1d920000-00007efc1d92d000	Deferred        libxrender.so.1
ELF	00007efc1d92d000-00007efc1d934000	Deferred        libxxf86vm.so.1
ELF	00007efc1d934000-00007efc1d939000	Deferred        libxinerama.so.1
ELF	00007efc1d939000-00007efc1d93f000	Deferred        libxau.so.6
ELF	00007efc1d93f000-00007efc1d96b000	Deferred        libxcb.so.1
ELF	00007efc1d96b000-00007efc1dab3000	Deferred        libx11.so.6
ELF	00007efc1dab3000-00007efc1dac7000	Deferred        libxext.so.6
ELF	00007efc1dac9000-00007efc1dad6000	Deferred        libxcursor.so.1
ELF	00007efc1dad7000-00007efc1db6a000	Deferred        winex11.so
ELF	00007efc1db6a000-00007efc1dca8000	Deferred        opengl32.so
ELF	00007efc1dd9b000-00007efc1ddc8000	Deferred        libexpat.so.1
ELF	00007efc1ddc8000-00007efc1de16000	Deferred        libfontconfig.so.1
ELF	00007efc1de16000-00007efc1de5e000	Deferred        libpcre.so.1
ELF	00007efc1de5e000-00007efc1de81000	Deferred        libbrotlicommon.so.1
ELF	00007efc1de81000-00007efc1dea5000	Deferred        libgraphite2.so.3
ELF	00007efc1dea5000-00007efc1dfde000	Deferred        libglib-2.0.so.0
ELF	00007efc1dfde000-00007efc1dfeb000	Deferred        libbrotlidec.so.1
ELF	00007efc1dfeb000-00007efc1e0f4000	Deferred        libharfbuzz.so.0
ELF	00007efc1e0f4000-00007efc1e12e000	Deferred        libpng16.so.16
ELF	00007efc1e12e000-00007efc1e142000	Deferred        libbz2.so.1
ELF	00007efc1e142000-00007efc1e300000	Deferred        win32u.so
ELF	00007efc1e884000-00007efc1e945000	Deferred        libfreetype.so.6
ELF	00007efc1ea9c000-00007efc1eab7000	Deferred        libz.so.1
ELF	00007efc1eab7000-00007efc1eae1000	Deferred        liblzma.so.5
ELF	00007efc1eae1000-00007efc1eb02000	Deferred        libgcc_s.so.1
ELF	00007efc1eb02000-00007efc1ebe5000	Deferred        libm.so.6
ELF	00007efc1ebe5000-00007efc1ec00000	Deferred        libunwind.so.8
ELF	00007efc1ec00000-00007efc1ee0e000	Deferred        libc.so.6
ELF	00007efc1ee26000-00007efc1ef0e000	Dwarf           ntdll.so
ELF	00007efc1ef23000-00007efc1ef5c000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	0000007c    0     wine_rpcrt4_io
	0000009c    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000c4    0     
	000000e4    0     wine_rpcrt4_io
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	000000c0    0     
00000068 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	00000080    0     
	00000084    0     
	00000088    0     
	00000094    0     
	00000098    0     
0000008c plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000090    0     
	000000a0    0     
	000000a4    0     wine_sechost_service
	000000a8    0     wine_rpcrt4_server
000000ac svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000b0    0     
	000000b8    0     
	000000bc    0     wine_sechost_service
000000c8 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	000000cc    0     
	000000d0    0     
	000000d4    0     wine_rpcrt4_server
000000dc rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000e0    0     
	000000ec    0     
	000000f0    0     wine_sechost_service
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_server
	000000fc    0     wine_rpcrt4_io
	000001ac    0     wine_rpcrt4_io
00000104 (D) Z:\home\luis\.var\app\io.github.vinegarhq.Vinegar\data\vinegar\prefix\vinegar\versions\version-5a3824df86134561\RobloxStudioBeta.exe
	["Z:\home\luis\.var\app\io.github.vinegarhq.Vinegar\data\vinegar\prefix\vinegar\versions\version-5a3824df86134561\RobloxStudioBeta.exe" ]
	00000108    0 <== 
	0000010c   15     
	00000110    0     
	00000114    0     
	00000118    0     
	0000011c    0     
	00000120    0     
	00000124    0     
	00000128    0     
	0000012c    0     
	00000130    0     
	00000134    0     
	00000138    0     
	00000140    0     
	00000144    0     
	00000148    0     
	0000014c    0     
	00000150    0     
	00000154    0     
	00000158    0     
	0000015c    0     
	00000160    0     
	00000164    0     
	00000168    0     
	0000016c    0     
	00000170    0     
	00000174    0     
	00000178    0     
	0000017c    0     
	00000180    0     
	00000184    0     
	00000188    0     
	0000018c    0     
	000001bc    0     CrashRep
	000001c0    0     CrashRep
	000001c4    0     ErrorUpl
	000001c8    0     Deferred
	000001cc    0     HttpThre
	000001d4    0     wine_threadpool_worker
	000001dc    0     wine_threadpool_waitqueue
	000001e4    0     PluginLo
	000001e8    0     PluginLo
	000001ec    0     PluginLo
	000001f0    0     PluginLo
	000001f4    0     PluginLo
	000001f8    0     PluginLo
	000001fc    0     PluginLo
	00000200    0     PluginLo
	00000204    0     EventIng
	00000208    0     wine_rpcrt4_server
	0000020c    0     
	00000210    0     wined3d_cs
	00000214    0     
	00000218    0     
	0000021c    0     
0000019c explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	000001a0    0     
	000001a4    0     
	000001a8    0     wine_rpcrt4_server
System information:
    Wine build: v8.5 (Staging)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 6.4.11-200.fc38.x86_64

I need help to fix please. Normal Roblox works fine it is just Studio thats broken i even tried reinstall.

**Comment by mr-sihc** [comment] 2023-08-24 19:31
you use very old wine, UPDATE WINE WTF

**Comment by Username404-59** [comment] 2023-08-24 20:08
> you use very old wine, UPDATE WINE WTF
[The flatpak's wine version has been downgraded to 8.5](https://github.com/flathub/io.github.vinegarhq.Vinegar/pull/27/commits/ea4f0f83e7bb2387c237b5edc9754fd6cbf80082)

From what I've understood more recent versions don't work with the roblox player, although I haven't checked myself

**Comment by Thelolguy1** [comment] 2023-08-24 20:22
Can confirm, Roblox Studio is non-functional at the moment.

**Comment by mr-sihc** [comment] 2023-08-27 15:49
works for me (proton ge 14, D3D10 with dxvk)

**Comment by Thelolguy1** [comment] 2023-08-31 01:26
duplicate of #74 , let's keep it there

**Closed by Thelolguy1** 2023-08-31 01:26 UTC
