### ISSUE TITLE
[Bug] Roblox encountered an unexpected error 

### ISSUE THREAD

**Issue by Davilarek** [vinegarhq/vinegar#393] opened 2024-02-25 11:49 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![obraz](https://github.com/vinegarhq/vinegar/assets/62715937/1c8ea58c-f35c-4183-b760-0da47ae1a125)
It was working about a week ago
[Player-2024-02-25T12:41:46+01:00.log](https://github.com/vinegarhq/vinegar/files/14396207/Player-2024-02-25T12.41.46%2B01.00.log)
Using flatpak on ArchLinux

### System information

```shell
* Vinegar: v1.7.4 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 5 3600 6-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.6-arch1-1
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:05:00.0 /sys/class/drm/card0
```

**Comment by apprehensions** [comment] 2024-02-25 12:28
You have not read the preliminary instructions.

Duplicate of #392

**Closed by apprehensions** 2024-02-25 12:28 UTC
Labels: bug

**Comment by Davilarek** [comment] 2024-02-25 12:33
I did, the search didn't result in any issues related to my title.
