### ISSUE TITLE
Vinegar crashes on launch.

### ISSUE THREAD

**Issue by jackyard86** [vinegarhq/vinegar#343] opened 2024-01-19 09:00 UTC
#### Describe the bug

Vinegar crashes on launch and shows this error: 
![2024-01-19-174654_1920x1200_scrot](https://github.com/vinegarhq/vinegar/assets/128217480/e6c52f70-59cb-4218-ba0c-25e9c1209749)

"Show Details" button doesn't do anything but crashes the Wine debugger.

Occasionally it launches and plays for a few minutes, but after that it crashes the same.

I tried deleting files under .var and reinstalling Vinegar but had no avail.

#### To Reproduce

1. Launch Vinegar.
2. It crashes.

### Logs

[log.txt](https://github.com/vinegarhq/vinegar/files/13986502/log.txt)

### System information

$ flatpak run org.vinegarhq.Vinegar sysinfo
* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 12th Gen Intel(R) Core(TM) i3-12100F
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.7.0-arch3-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:01:00.0 /sys/class/drm/card1

**Comment by apprehensions** [comment] 2024-01-19 10:02
Duplicate of #342

**Closed by apprehensions** 2024-01-19 10:02 UTC
Labels: bug
