### ISSUE TITLE
Vinegar crashes after being launched for a few seconds

### ISSUE THREAD

**Issue by thedirptastic** [vinegarhq/vinegar#346] opened 2024-01-24 00:01 UTC
#### Describe the bug
- [yes] I have searched open and closed issues to make sure that the bug has not yet been reported
- [yes] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

Whenever I run vinegar, it closes after a few seconds. I believe this is happening due to Vinegar receiving a KILL command.

#### To Reproduce
All I did was do a fresh install of Vinegar through flatpak. Whenever I ran the command to launch the player, it will get partly through the command, before crashing. In my terminal, it says the end code as KILL, meaning that the process was killed

### Logs
Log has been attached, along with a video of me running the command

### System information

* Installation method:

```
* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.0-arch3-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:02:00.0 /sys/class/drm/card0
```
[Player-2024-01-23T15:55:57-08:00.log](https://github.com/vinegarhq/vinegar/files/14030963/Player-2024-01-23T15.55.57-08.00.log)

https://github.com/vinegarhq/vinegar/assets/80712226/615ef598-a3a2-43e6-b507-52ddfd7b043b

**Comment by apprehensions** [comment] 2024-01-24 03:55
Duplicate of #342

**Closed by apprehensions** 2024-01-24 03:55 UTC
Labels: bug

**Comment by lunarlettuce** [comment] 2024-01-24 06:41
I'm sorry for laughing, but your animation for window closing is hilarious

**Comment by thedirptastic** [comment] 2024-01-24 21:13
> Duplicate of #342

I already have that in my config, it is not a duplicate

**Comment by thedirptastic** [comment] 2024-01-24 21:22
I found a solution. I am using the AUR version with wine-ge. It seems to work but has weird behavior when tabbing in or out of the game.
