### ISSUE TITLE
Lag in high quality settings on steam deck

### ISSUE THREAD

**Issue by kalenhop9** [vinegarhq/vinegar#142] opened 2023-09-05 23:23 UTC
Whenever I play Roblox on max quality settings I get a LOT of lag.
Is there a way to get better performance on MAX quality settings?

**Comment by mr-sihc** [comment] 2023-09-06 01:24
They could try re-adding the RCO flags if they work again

**Comment by rockyamethyst** [comment] 2023-09-06 01:33
1. Have you tried using [wine-ge](https://github.com/GloriousEggroll/wine-ge-custom/tree/master)?
2. Have you tried using ESync/Fsync?


Also please, ask in the [discord server](https://discord.gg/dzdzZ6Pps2), it's way easier to assist there.

**Comment by mr-sihc** [comment] 2023-09-06 14:58
1. wine-ge and wine have similar performance
2. ESync is standard on

BUT, you can try different graphics modes, like D3D11/Vulkan.
They say D3D11 has better performance with DXVK than Vulkan, but you can still try.

Also Roblox is laggy on Windows too, it's really unoptimized so don't feel bad about it not working good.
When you play a less demanding game on Roblox you can higher the settings
but otherwise, there's probably not much you can do...
(other than waiting for the RCO flags to work again if they'll ever, and then them implementing them back in vinegar)

**Comment by Cristiandis** [comment] 2023-09-06 15:08
Also you can only use Fsync with wine-ge

**Comment by mr-sihc** [comment] 2023-09-06 15:34
and a kernel patch, that SteamOS doesn't have

**Comment by rockyamethyst** [comment] 2023-09-06 16:19
> 1. wine-ge and wine have similar performance

That's weird, it boosted my fps to a way more playable one (from 30-40 up to 70-90), guess it's a case-by-case thing? still worth a try.

> 2. ESync is standard on

Did not know that, assumed it's not by default since the configuration webpage does not talk about it, only the tips and tricks, which doesn't even say if it's on by default or not.

Also damn, really? Debian's stock kernel has FSync support but not SteamOS'? That's funky.

**Comment by mr-sihc** [comment] 2023-09-06 17:32
1. Did you try that on Roblox Vinegar? For me vinegar doesn't even start without wine-ge.
2. You can see that when you start vinegar player in the console.

Yeah, SteamOS is Arch-based and the default Arch kernel doesn't have it either.

**Comment by rockyamethyst** [comment] 2023-09-06 17:49
1. Yeah, my (flatpak) vinegar starts fine without setting it to use wine-ge
2. ik, never exactly payed attention to logs with the default conf

Another Arch L in my book :skull:

**Comment by Cristiandis** [comment] 2023-09-06 17:56
I believe that fysnc support was added in kernel version 5.16 so arch should, tho steamos uses kernel 5.15 i believe

>

**Comment by Cristiandis** [comment] 2023-09-06 17:58
![Uploading Screenshot_20230906_195744_Lemur Browser.jpg…]()

**Comment by Cristiandis** [comment] 2023-09-06 17:58
![Screenshot_20230906_195744_Lemur Browser](https://github.com/vinegarhq/vinegar/assets/112336919/9ca054d2-69af-4db2-b579-76448de400f9)

**Comment by mr-sihc** [comment] 2023-09-06 18:09
**Please don't spam.**

*This is false information.*
The (at least) Arch kernel has to be patched for it to work.

And steamos uses kernel version 6.1.43, i tested, it does not work.
It does not work stock.

You can get another kernel like, linux-zen on arch, that has those patches.

**Comment by mr-sihc** [comment] 2023-09-06 18:17
> 1. Yeah, my (flatpak) vinegar starts fine without setting it to use wine-ge

The flatpack version of vinegar seems to be bundled with it's own version of wine. (since i can't find an installation of wine on the deck, and vinegar is a very big installation)
This one, is, of course patched or selected version of wine that does obviously work.

(but really if i had to have 10 different version of wine or whatever installed on my system without knowing, we'd have arrived at windows levels of stupidity)

**Comment by kalenhop9** [comment] 2023-09-06 21:32
How do I use D3D11 for the render of Roblox Vingear?

**Comment by mr-sihc** [comment] 2023-09-07 10:21
> **Please don't spam.**
> 
> _This is false information._ The (at least) Arch kernel has to be patched for it to work.
> 
> It does not work stock.
> 
> You can get another kernel like, linux-zen on arch, that has those patches.
> 
> And steamos uses kernel version 6.1.43, i tested, it does not work.

actually, forget that, i've been using linux for so long, i didn't realize that they merged that mainline, since also only used linux-zen, but after realizing it's trash, i now confirmed
the patch is no longer needed, it is standard

and for the that i tried it on steam deck, i did everything correctly, but it seems like vinegar's wine doesn't have fsync patched into it, so that's why it failed there, i tried it on lutris again, and that worked

so that's that

**Comment by mr-sihc** [comment] 2023-09-07 10:22
> How do I use D3D11 for the renderer of Roblox Vinegar?

that's standard used
D3D11 and DXVK are the standard conf, but if you want to change that, you can go to:
https://vinegarhq.github.io/Configuration/index.html

scroll down, and you find info's and examples of how to configure the renderer

**Comment by mr-sihc** [comment] 2023-09-07 10:25
@apprehensions

so that i saw that you disliked the comment i assume you won't add RCO back...

but why?
weren't they the number 1. thing that made roblox ultra fast?
why is not getting added back?

**Comment by apprehensions** [comment] 2023-09-07 14:15
They did not make roblox 'ultra fast', they made it have a performance improvement enough to warrant it to be part of Vinegar; at the cost of RCO being very unstable and preventing Roblox from running, having extremely bad performance at times.

We are going to use RFO soon.

**Comment by mr-sihc** [comment] 2023-09-07 18:43
> They did not make roblox 'ultra fast', they made it have a performance improvement enough to warrant it to be part of Vinegar; at the cost of RCO being very unstable and preventing Roblox from running, having extremely bad performance at times.
> 
> We are going to use RFO soon.

oh ok.
I got this from the post on the roblox forum (https://devforum.roblox.com/t/vinegar-the-better-way-to-run-roblox-on-linux/2224394)

![grafik](https://github.com/vinegarhq/vinegar/assets/85245131/5f9d9bf6-4eb4-436d-a3a0-acb91aa1d9be)

**Closed** 2023-09-07 22:52 UTC
