### ISSUE TITLE
"This application encountered an unrecoverable error"

### ISSUE THREAD

**Issue by Vortex1232j** [vinegarhq/vinegar#135] opened 2023-09-02 03:20 UTC
I need help
![Screenshot 2023-09-02 11 18 47 AM](https://github.com/vinegarhq/vinegar/assets/143853579/c154b778-3d7a-4c7b-8daf-ed1869498c3c)

**Comment by Vortex1232j** [comment] 2023-09-02 03:22
Installed from flatpak 
Cpu intel

**Comment by Thelolguy1** [comment] 2023-09-02 03:50
What generation of CPU?

**Comment by Vortex1232j** [comment] 2023-09-02 04:04
I dont really know it says this Intel(R) Celeron(R) N4500 @ 1.10GHz (2 threads, 2.80GHz)

**Comment by Thelolguy1** [comment] 2023-09-02 05:32
It's possible that you will not be able to play Roblox on Linux due to a lack of AVX support on your processor. However, you will still be able to play on Windows.

**Comment by bobeatsshit** [comment] 2023-09-03 12:22
i have the same problem but with the intel core i5 6300U but it sais on the intel website that it has avx2 support

**Comment by SomeOrdinaryDude** [comment] 2023-09-03 12:45
Same issue. It worked then suddenly didn't, and I have a modern Ryzen 9 5950X CPU.

**Comment by tseli0s** [comment] 2023-09-03 18:06
Same issue here as well, was working mostly fine but now I get this error. My CPU is kind of old (R5 1500X).

**Comment by Wrenderbender** [comment] 2023-09-03 23:25
Potential duplicate of #134. Should be closed

**Comment by Thelolguy1** [comment] 2023-09-04 05:43
@Wrenderbender Because we have no way of actually figuring out the cause of these errors just from the given information, we cannot say for certain they are duplicates.

**Comment by Thelolguy1** [comment] 2023-09-04 05:59
@bobeatsshit @tseli0s @SomeOrdinaryDude @Vortex1232j Please try wiping the flatpak installation completely. This can be done by running ```flatpak remove io.github.vinegarhq.Vinegar --delete-data``` and then running ```flatpak install io.github.vinegarhq.Vinegar```. Additionally, some people have reported issues with Wine-GE on the latest build. The newest version of Wine should provide comparable performance to Wine-GE in any situation.

**Comment by Wrenderbender** [comment] 2023-09-04 06:25
sorry about that @Thelolguy1

**Comment by Thelolguy1** [comment] 2023-09-04 06:27
No worries, please message me if you encounter any trouble

**Comment by bobeatsshit** [comment] 2023-09-04 19:05
got it working by reinstalling wine on flatpak or installing or idk if this did anything i removed wine using flatpak run io.github.vinegarhq.Vinegar uninstall and flatpak run io.github.vinegarhq.Vinegar delete

**Comment by Thelolguy1** [comment] 2023-09-04 20:37
@bobeatsshit glad to hear it's working

**Comment by tseli0s** [comment] 2023-09-06 09:48
> @bobeatsshit @tseli0s @SomeOrdinaryDude @Vortex1232j Please try wiping the flatpak installation completely. This can be done by running flatpak remove io.github.vinegarhq.Vinegar --delete-data and then running flatpak install io.github.vinegarhq.Vinegar. Additionally, some people have reported issues with Wine-GE on the latest build. The newest version of Wine should provide comparable performance to Wine-GE in any situation.

Yep, that did it. I actually completely purged the directory after uninstalling. Anyways, yes, this is a fix, but since we don't know why it's caused, it may be worth further testing this issue.

**Comment by mr-sihc** [comment] 2023-09-09 19:40
Can this be closed? We already know the issue comes from people buying shit CPUs.

**Comment by apprehensions** [comment] 2023-09-09 19:42
This issue is still prevalent on many users, and the CPU is not the cause.

We are still figuring out a fix for this...

**Comment by bobeatsshit** [comment] 2023-09-09 20:43
Well you still need a copy with avx2 instructions

**Comment by ulibte** [comment] 2023-09-16 18:48
> It's possible that you will not be able to play Roblox on Linux due to a lack of AVX support on your processor. However, you will still be able to play on Windows.

 i’m curious to understand why this might be the case. could you please explain why a cpu without avx would work on windows but not on wine?

**Comment by TheMemeSniper** [comment] 2023-09-20 01:29
suddenly started happening to me on the AUR package, CPU AMD Ryzen 5 5600H with Radeon Graphics

**Comment by TheMemeSniper** [comment] 2023-09-20 01:40
installing the flatpak seems to fix it, maybe an incompatibility with the current version of wine in the arch repos?

**Comment by Cristiandis** [comment] 2023-09-20 04:30
Wine 8.16 is broken at the moment

**Closed** 2023-09-21 22:20 UTC

**Comment by CoWinkKeyDinkInc** [comment] 2023-09-22 18:24
> Wine 8.16 is broken at the moment

Correct, though it seems there are multiple causes to this issue. I manually downgraded to Wine 8.15 in Arch (as I use the AUR version) and it worked for me.
