### ISSUE TITLE
Roblox doesn't start

### ISSUE THREAD

**Issue by jordanoff83** [vinegarhq/vinegar#333] opened 2024-01-12 18:10 UTC
#### Describe the bug
- [ ] I have searched open and closed issues to make sure that the bug has not yet been reported
- [ ] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

Roblox app cant start with the following message: 
"Vinegar experienced an error: fetch version-88cfc23f4e7d4e4b package manifest: bad status: 403 Forbidden"

#### To Reproduce
Start Roblox app or start via roblox website.

### Logs

"2024/01/12 20:03:38 binary.go:260: Failed to merlin: merlin: bad status: 405 Method Not Allowed
2024/01/12 20:03:38 deployment.go:41: Fetching latest version of WindowsPlayer for channel live
2024/01/12 20:03:38 deployment.go:48: Fetched WindowsPlayer canonical version 0.607.0.6070550
2024/01/12 20:03:38 binary.go:275: Installing WindowsPlayer ( -> version-88cfc23f4e7d4e4b)
2024/01/12 20:03:38 cdn.go:23: Finding an accessible Roblox deploy mirror
2024/01/12 20:03:38 cdn.go:35: Found deploy mirror: https://setup.rbxcdn.com
2024/01/12 20:03:38 pkg_manifest.go:48: Fetching manifest for version-88cfc23f4e7d4e4b (https://setup.rbxcdn.com/channel/live/version-88cfc23f4e7d4e4b-rbxPkgManifest.txt)
2024/01/12 20:03:39 vinegar.go:219: fetch version-88cfc23f4e7d4e4b package manifest: bad status: 403 Forbidden
2024/01/12 20:03:41 splash.go:189: Opening log file: /home/jordan/.cache/vinegar/logs/Player-2024-01-12T20:03:33+02:00.log"

### System information

* Installation method:
* Installed via AUR

#### Additional context
Vinegar previously worked fine until yesterday on two different linux computers with two different accounts at my home.

**Comment by apprehensions** [comment] 2024-01-12 18:11
You did not read the issue template. You did not read other issues, nor fill any system information.

Duplicate of #332

**Closed by apprehensions** 2024-01-12 18:11 UTC
Labels: bug

**Comment by jordanoff83** [comment] 2024-01-12 19:04
Thank you!
