### ISSUE TITLE
Vinegar won't start Roblox

### ISSUE THREAD

**Issue by Heus-Sueh** [vinegarhq/vinegar#331] opened 2024-01-09 23:48 UTC
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

https://bin.disroot.org/?fabb07f807b83da6#A9CeHu6QbmtBdTQaKZjJDGbj9qWg4ySopzKS6YRR1c8q

#### To Reproduce
I don't know

### Logs
[Player-2024-01-09T20:41:10-03:00.log](https://github.com/vinegarhq/vinegar/files/13881292/Player-2024-01-09T20.41.10-03.00.log)

### System information

* Installation method: Flatpak

❯ flatpak run org.vinegarhq.Vinegar sysinfo
* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.9-200.fc39.x86_64
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:01:00.0 /sys/class/drm/card0

#### Additional context
I haven't run Vinegar in a while and I tried to open it today and got this error

**Comment by apprehensions** [comment] 2024-01-10 05:02
Duplicate of #233

**Closed by apprehensions** 2024-01-10 05:02 UTC
Labels: bug
