### ISSUE TITLE
its can't be luanch at all 

### ISSUE THREAD

**Issue by ASERPRO45** [vinegarhq/vinegar#413] opened 2024-05-08 21:34 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/vinegarhq/vinegar/assets/97183759/938bb8c4-0f95-4174-9738-36f2ef150382)
its be like this for seconds and when its done nothing open ?

**Comment by tristann21** [comment] 2024-05-08 23:03
> ### Acknowledgement of preliminary instructions
> 
>     * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> 
> ### What problem did you encounter?
> 
> ![image](https://private-user-images.githubusercontent.com/97183759/329059621-938bb8c4-0f95-4174-9738-36f2ef150382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDk2NDIsIm5iZiI6MTcxNTIwOTM0MiwicGF0aCI6Ii85NzE4Mzc1OS8zMjkwNTk2MjEtOTM4YmI4YzQtMGY5NS00MTc0LTk3MzgtMzZmMmVmMTUwMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDIzMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTRjM2FiZTNiYzZiNmMyMTA5NjQ0MzE5NjFlMTM3ZGVhYmRkOTViMjYxOTg5NTA1NDRhNDdiNmFmNDQ4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zIDfnFpKaoGCXoKTyVjpuLagYRlT6FHmZeEqP0ABJMc) its be like this for seconds and when its done nothing open ?
> ### System information
> 
> _No response_

Only studio is supported on Linux, Roblox player is blocked.

pls wait for a response next time

**Comment by apprehensions** [comment] 2024-05-09 02:34
As stated in the README:

> As of the 2nd of March, 2024, Roblox has blocked the use of Wine to access the Roblox Player. More information can be found [here](https://vinegarhq.org/Home/rol_faq.html).

Duplicate of #398

**Closed by apprehensions** 2024-05-09 02:34 UTC
Labels: bug
