### ISSUE TITLE
Vinegar experienced an error: failed to run roblox: exit status 1 on Roblox Studio open

### ISSUE THREAD

**Issue by rag3trey** [vinegarhq/vinegar#403] opened 2024-03-01 19:31 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Each time I open Roblox Studio (which is not part of the Wine block according to https://vinegarhq.org/Home/rol_faq.html) I get the error stated in the title. Note: I understand that **Roblox Player** is blocked now and will not work. However I do not have access to **Roblox Studio**. I have searched all closed or open issues and have not found any sort of solution to this error. Any help that I can get would be greatly appreciated.

Log file:
[Studio-2024-03-01T11:54:42-06:00.log](https://github.com/vinegarhq/vinegar/files/14465160/Studio-2024-03-01T11.54.42-06.00.log)

### System information

```shell
flatpak run org.vinegarhq.Vinegar  sysinfo
* Vinegar: v1.7.4 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 7 7700X 8-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.10-76060610-generic
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:10:00.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1
```

**Comment by rag3trey** [comment] 2024-03-01 19:39
Additionally, I do see `However, Roblox may sometimes include breaking changes into Studio that result in several days of downtime while Wine or RoL maintainers fix the issue`. Is anyone else having Studio problems currently?

**Comment by apprehensions** [comment] 2024-03-01 19:52
You have not read the preliminary instructions.

https://vinegarhq.org/Troubleshooting/index.html#stale-wineserver

**Comment by apprehensions** [comment] 2024-03-01 19:55
Why did you make a new issue? 

Duplicate of #402

**Closed by apprehensions** 2024-03-01 19:55 UTC
Labels: bug

**Comment by rag3trey** [comment] 2024-03-01 19:59
> You have not read the preliminary instructions.
> 
> https://vinegarhq.org/Troubleshooting/index.html#stale-wineserver

I am not sure how this answers my issue. It happens when I try to authorize access to Roblox Studio. Would this not be a valid issue?

**Comment by apprehensions** [comment] 2024-03-01 20:01
Update Vinegar.

> In the new v1.7.4 release, a new WebView installer has been officially introduced, which only gets activated on first run, to install it on Studio (change to `player` if necessary):
```
vinegar -firstrun studio run
```

**Comment by rag3trey** [comment] 2024-03-01 20:03
> Update Vinegar.
> 
> > In the new v1.7.4 release, a new WebView installer has been officially introduced, which only gets activated on first run, to install it on Studio (change to `player` if necessary):
> 
> ```
> vinegar -firstrun studio run
> ```

```
flatpak run org.vinegarhq.Vinegar -firstrun studio run
2024/03/01 14:02:36 INFO Logging to file path=/home/trey/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Studio-2024-03-01T14:02:36-06:00.log
2024/03/01 14:02:36 INFO Initializing wineprefix dir=/home/trey/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefixes/studio
02ec:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
2024/03/01 14:02:36 ERROR init Studio: failed to init Studio prefix: exit status
```

**Comment by apprehensions** [comment] 2024-03-01 20:11
As I said, you have not read the preliminary instructions nor have you done the solution to your problem's outcome.

You need to fix that before you do anything.

**Comment by rag3trey** [comment] 2024-03-01 20:13
> As I said, you have not read the preliminary instructions nor have you done the solution to your problem's outcome.
> 
> You need to fix that before you do anything.

Alrighty. I will look through the troubleshooting link about stale wineserver to see if I missed anything when I was doing my troubleshooting.
