### ISSUE TITLE
vinegar installation bug

### ISSUE THREAD

**Issue by Nana-Nti** [vinegarhq/vinegar#62] opened 2023-04-27 15:32 UTC
when i install the flatpak for vinegar it doesnt give me the icons for it? is this a bug because i copied the code into linux terminal and the icons dont seem to be there? help me

**Comment by somerandomguy24** [comment] 2023-04-27 19:23
They mentioned flatpak in their comment:
> i install the flatpak for vinegar

If that is not what was meant and instead where the flatpak was installed from (gnome software, discover, flathub, etc), you should probably mention that.

**Comment by apprehensions** [comment] 2023-04-27 21:40
> i copied the code into linux terminal

it wasn't made sure what instructions they had followed to install Vinegar, if they used documentation (no code, just a CLI flatpak install), or used a GUI (Gnome Software). either way, installation should be flawless.

Though, this issue is unsolved and i have no way of knowing what has been causing it.

cc: @Thelolguy1

**Comment by Thelolguy1** [comment] 2023-04-28 00:11
Can't reproduce, I haven't heard of any reports regarding broken icons and my own installation is working. Additionally, I haven't pushed any updates to it, so perhaps it is a one time fluke.

**Comment by Thelolguy1** [comment] 2023-04-28 00:11
Additionally, make sure you are searching "Roblox Player" or "Roblox Studio"; we don't have icons for Vinegar itself.

**Comment by Thelolguy1** [comment] 2023-05-01 18:52
Closing until new information is received.

**Closed by Thelolguy1** 2023-05-01 18:52 UTC
Labels: question
