### ISSUE TITLE
RibbonConfig not allowing roblox studio to be installed.

### ISSUE THREAD

**Issue by mrfiguy** [vinegarhq/vinegar#436] opened 2024-09-25 03:22 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/acc8443d-e016-4e3e-9cb2-e6935299fd00)
Each time i try to open roblox studio it just gives me this error. I've restarted and even updated my device. I havn't tried reinstalling studio, but in doing so it wipes all of my data from my studio directory. (i have made backups of my directory) 
[Studio-2024-09-24T23:20:29-04:00.log](https://github.com/user-attachments/files/17124069/Studio-2024-09-24T23.20.29-04.00.log)

**Comment by apprehensions** [comment] 2024-09-25 03:29
Duplicate of #435

**Closed by apprehensions** 2024-09-25 03:29 UTC
Labels: bug
