### ISSUE TITLE
unable to execute roblox studio due to an error wile dowloading

### ISSUE THREAD

**Issue by fernando433566** [vinegarhq/vinegar#438] opened 2024-09-29 09:49 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

one day i wanted to go to studio to make a game but this error message pops up
"Vinegar experienced an error:
failed to setup roblox: install version-1e5deb86743148f7: setup: unhandled package: RibbonConfig.zip"
i dont know how why i get this error, but i use arch linux if that helps i add the log file if that helps too 

Sep 29 11:42:31.665 INF Fetching Binary Deployment name=WindowsStudio64 channel=""
Sep 29 11:42:32.007 INF Fetched Binary Deployment! name=WindowsStudio64 channel="" guid=version-1e5deb86743148f7 version=0.644.0.6440702
Sep 29 11:42:32.007 INF Installing Binary name=WindowsStudio64 old_guid="" new_guid=version-1e5deb86743148f7
Sep 29 11:42:32.008 INF Finding an accessible deploy mirror
Sep 29 11:42:32.407 INF Found deploy mirror mirror=https://setup.rbxcdn.com
Sep 29 11:42:32.414 INF Installing Packages guid=version-1e5deb86743148f7 count=66
Sep 29 11:42:32.414 INF Verifying Package name=WebView2RuntimeInstaller.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/e42a6697bf05466d4dba26c8fe476d2e
Sep 29 11:42:32.414 INF Verifying Package name=content-sky.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/1d0390337d1a4a58e5514be1a9481ad6
Sep 29 11:42:32.414 INF Verifying Package name=WebView2.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/e83a453f974f722e85e19facaa1e265e
Sep 29 11:42:32.414 INF Verifying Package name=ApplicationConfig.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9e7221ad4d25d7348de5f887cade14dd
Sep 29 11:42:32.414 INF Verifying Package name=content-api-docs.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/570898d70d651811635272ccb9431bcf
Sep 29 11:42:32.414 INF Verifying Package name=content-terrain.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b4b75c21ce05378163042dc45cec5834
Sep 29 11:42:32.414 INF Verifying Package name=ssl.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9db266898c508ffdbb4cba815a6e7250
Sep 29 11:42:32.414 INF Verifying Package name=LibrariesQt5.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/24859039f675506de20e49abdf53c5d9
Sep 29 11:42:32.414 INF Verifying Package name=content-configs.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/15db252031b4cfb1cba340e150f9cd63
Sep 29 11:42:32.414 INF Verifying Package name=Qml.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/4377ceffa9c701ab550c0ef8c88f96d7
Sep 29 11:42:32.414 INF Verifying Package name=Libraries.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9319c87769b30fcb87f41529b4640603
Sep 29 11:42:32.415 INF Verifying Package name=content-textures2.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9ba94e86704c5a6fca3f79c7077eae53
Sep 29 11:42:32.414 INF Verifying Package name=StudioFonts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/6df04925b4a61fdf50c06ff827eb369a
Sep 29 11:42:32.415 INF Verifying Package name=extracontent-luapackages.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b2769609c7d8e0e80d491418e4f8278a
Sep 29 11:42:32.415 INF Package is already downloaded name=ApplicationConfig.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9e7221ad4d25d7348de5f887cade14dd
Sep 29 11:42:32.414 INF Verifying Package name=extracontent-scripts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/edd3a2085b5af81f83b08315e219fea4
Sep 29 11:42:32.415 INF Package is already downloaded name=content-terrain.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b4b75c21ce05378163042dc45cec5834
Sep 29 11:42:32.415 INF Verifying Package name=content-avatar.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/4df27fd9bd6d765be81ff60a128c84d4
Sep 29 11:42:32.415 INF Verifying Package name=shaders.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/ae3c92ffefd4506df2133c68917ffd79
Sep 29 11:42:32.415 INF Verifying Package name=content-models.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/a94b6d53eea3ae5600fc749c1a0bd8cc
Sep 29 11:42:32.415 INF Verifying Package name=content-platform-fonts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/8f379ec2b22ff106b837d79f7fdbf0d8
Sep 29 11:42:32.415 INF Verifying Package name=content-textures3.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/909f4b9d7bc03a926d35e84d0c99ffbf
Sep 29 11:42:32.416 INF Verifying Package name=extracontent-textures.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/25fcea18f4f97a129d9322e399a5fe6f
Sep 29 11:42:32.416 INF Verifying Package name=content-fonts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/30c885074d0320c0932e06bfd537c915
Sep 29 11:42:32.416 INF Verifying Package name=BuiltInPlugins.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/544180af6b3324ea2f6e431812475c6e
Sep 29 11:42:32.416 INF Verifying Package name=BuiltInStandalonePlugins.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b9cb02ea4579a4ea07e6dbb0edd4059c
Sep 29 11:42:32.414 INF Verifying Package name=content-studio_svg_textures.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/f07b60093a555eb259986b65a526d52d
Sep 29 11:42:32.416 INF Verifying Package name=RobloxStudio.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/124feceb20d6de3ce913a82088907541
Sep 29 11:42:32.414 INF Verifying Package name=content-qt_translations.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9ac41564393da36084990e6dd9d08f50
Sep 29 11:42:32.414 INF Verifying Package name=Plugins.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b4b04085aaf099cec525e5368992fbf5
Sep 29 11:42:32.414 INF Verifying Package name=redist.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/c9622ecfbec2c14d30f390909c563124
Sep 29 11:42:32.414 INF Verifying Package name=content-sounds.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/cd77e0e77d698260809f8ae8b3993740
Sep 29 11:42:32.414 INF Verifying Package name=extracontent-models.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/8bbf6ff91646224355a16382e8fb38fa
Sep 29 11:42:32.420 INF Package is already downloaded name=content-api-docs.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/570898d70d651811635272ccb9431bcf
Sep 29 11:42:32.421 INF Extracted package name=content-terrain.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b4b75c21ce05378163042dc45cec5834 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/PlatformContent/pc/terrain
Sep 29 11:42:32.415 INF Verifying Package name=extracontent-translations.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/232866399eaaab39d09956b29c94efef
Sep 29 11:42:32.421 INF Package is already downloaded name=WebView2.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/e83a453f974f722e85e19facaa1e265e
Sep 29 11:42:32.421 INF Package is already downloaded name=content-configs.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/15db252031b4cfb1cba340e150f9cd63
Sep 29 11:42:32.421 INF Package is already downloaded name=ssl.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9db266898c508ffdbb4cba815a6e7250
Sep 29 11:42:32.421 INF Package is already downloaded name=content-models.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/a94b6d53eea3ae5600fc749c1a0bd8cc
Sep 29 11:42:32.422 INF Extracted package name=ApplicationConfig.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9e7221ad4d25d7348de5f887cade14dd dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ApplicationConfig
Sep 29 11:42:32.422 INF Package is already downloaded name=content-avatar.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/4df27fd9bd6d765be81ff60a128c84d4
Sep 29 11:42:32.422 INF Extracted package name=WebView2.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/e83a453f974f722e85e19facaa1e265e dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7
Sep 29 11:42:32.425 INF Package is already downloaded name=extracontent-translations.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/232866399eaaab39d09956b29c94efef
Sep 29 11:42:32.431 INF Package is already downloaded name=content-sounds.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/cd77e0e77d698260809f8ae8b3993740
Sep 29 11:42:32.431 INF Package is already downloaded name=Plugins.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b4b04085aaf099cec525e5368992fbf5
Sep 29 11:42:32.432 INF Package is already downloaded name=WebView2RuntimeInstaller.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/e42a6697bf05466d4dba26c8fe476d2e
Sep 29 11:42:32.433 INF Package is already downloaded name=content-qt_translations.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9ac41564393da36084990e6dd9d08f50
Sep 29 11:42:32.438 INF Package is already downloaded name=redist.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/c9622ecfbec2c14d30f390909c563124
Sep 29 11:42:32.440 INF Extracted package name=content-sounds.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/cd77e0e77d698260809f8ae8b3993740 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/sounds
Sep 29 11:42:32.441 INF Extracted package name=content-api-docs.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/570898d70d651811635272ccb9431bcf dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/api_docs
Sep 29 11:42:32.441 INF Package is already downloaded name=content-sky.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/1d0390337d1a4a58e5514be1a9481ad6
Sep 29 11:42:32.441 INF Extracted package name=content-configs.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/15db252031b4cfb1cba340e150f9cd63 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/configs
Sep 29 11:42:32.446 INF Package is already downloaded name=extracontent-scripts.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/edd3a2085b5af81f83b08315e219fea4
Sep 29 11:42:32.447 INF Package is already downloaded name=Qml.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/4377ceffa9c701ab550c0ef8c88f96d7
Sep 29 11:42:32.454 INF Package is already downloaded name=content-textures3.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/909f4b9d7bc03a926d35e84d0c99ffbf
Sep 29 11:42:32.458 INF Extracted package name=ssl.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9db266898c508ffdbb4cba815a6e7250 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ssl
Sep 29 11:42:32.464 INF Extracted package name=content-avatar.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/4df27fd9bd6d765be81ff60a128c84d4 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/avatar
Sep 29 11:42:32.464 INF Extracted package name=WebView2RuntimeInstaller.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/e42a6697bf05466d4dba26c8fe476d2e dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/WebView2RuntimeInstaller
Sep 29 11:42:32.473 INF Package is already downloaded name=content-fonts.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/30c885074d0320c0932e06bfd537c915
Sep 29 11:42:32.474 INF Package is already downloaded name=Libraries.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9319c87769b30fcb87f41529b4640603
Sep 29 11:42:32.474 INF Extracted package name=extracontent-translations.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/232866399eaaab39d09956b29c94efef dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ExtraContent/translations
Sep 29 11:42:32.478 INF Extracted package name=redist.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/c9622ecfbec2c14d30f390909c563124 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7
Sep 29 11:42:32.478 INF Package is already downloaded name=content-studio_svg_textures.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/f07b60093a555eb259986b65a526d52d
Sep 29 11:42:32.484 INF Extracted package name=content-qt_translations.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9ac41564393da36084990e6dd9d08f50 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/qt_translations
Sep 29 11:42:32.485 INF Extracted package name=Plugins.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b4b04085aaf099cec525e5368992fbf5 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/Plugins
Sep 29 11:42:32.486 INF Extracted package name=content-models.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/a94b6d53eea3ae5600fc749c1a0bd8cc dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/models
Sep 29 11:42:32.492 INF Package is already downloaded name=shaders.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/ae3c92ffefd4506df2133c68917ffd79
Sep 29 11:42:32.492 INF Package is already downloaded name=extracontent-models.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/8bbf6ff91646224355a16382e8fb38fa
Sep 29 11:42:32.495 INF Extracted package name=content-sky.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/1d0390337d1a4a58e5514be1a9481ad6 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/sky
Sep 29 11:42:32.513 INF Package is already downloaded name=LibrariesQt5.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/24859039f675506de20e49abdf53c5d9
Sep 29 11:42:32.514 INF Package is already downloaded name=content-textures2.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9ba94e86704c5a6fca3f79c7077eae53
Sep 29 11:42:32.516 INF Package is already downloaded name=content-platform-fonts.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/8f379ec2b22ff106b837d79f7fdbf0d8
Sep 29 11:42:32.528 INF Package is already downloaded name=extracontent-textures.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/25fcea18f4f97a129d9322e399a5fe6f
Sep 29 11:42:32.528 INF Extracted package name=extracontent-models.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/8bbf6ff91646224355a16382e8fb38fa dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ExtraContent/models
Sep 29 11:42:32.534 INF Package is already downloaded name=extracontent-luapackages.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b2769609c7d8e0e80d491418e4f8278a
Sep 29 11:42:32.570 INF Extracted package name=content-textures3.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/909f4b9d7bc03a926d35e84d0c99ffbf dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/PlatformContent/pc/textures
Sep 29 11:42:32.575 INF Package is already downloaded name=BuiltInStandalonePlugins.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b9cb02ea4579a4ea07e6dbb0edd4059c
Sep 29 11:42:32.646 INF Extracted package name=Qml.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/4377ceffa9c701ab550c0ef8c88f96d7 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/Qml
Sep 29 11:42:32.654 INF Package is already downloaded name=BuiltInPlugins.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/544180af6b3324ea2f6e431812475c6e
Sep 29 11:42:32.656 INF Extracted package name=Libraries.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9319c87769b30fcb87f41529b4640603 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7
Sep 29 11:42:32.661 INF Extracted package name=BuiltInStandalonePlugins.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b9cb02ea4579a4ea07e6dbb0edd4059c dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/BuiltInStandalonePlugins
Sep 29 11:42:32.691 INF Extracted package name=content-fonts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/30c885074d0320c0932e06bfd537c915 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/fonts
Sep 29 11:42:32.754 INF Extracted package name=extracontent-textures.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/25fcea18f4f97a129d9322e399a5fe6f dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ExtraContent/textures
Sep 29 11:42:32.794 INF Extracted package name=content-platform-fonts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/8f379ec2b22ff106b837d79f7fdbf0d8 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/PlatformContent/pc/fonts
Sep 29 11:42:32.796 INF Extracted package name=BuiltInPlugins.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/544180af6b3324ea2f6e431812475c6e dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/BuiltInPlugins
Sep 29 11:42:32.811 INF Extracted package name=shaders.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/ae3c92ffefd4506df2133c68917ffd79 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/shaders
Sep 29 11:42:32.827 INF Package is already downloaded name=RobloxStudio.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/124feceb20d6de3ce913a82088907541
Sep 29 11:42:32.842 INF Package is already downloaded name=StudioFonts.zip file=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/6df04925b4a61fdf50c06ff827eb369a
Sep 29 11:42:32.875 INF Extracted package name=LibrariesQt5.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/24859039f675506de20e49abdf53c5d9 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7
Sep 29 11:42:32.878 INF Extracted package name=extracontent-scripts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/edd3a2085b5af81f83b08315e219fea4 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ExtraContent/scripts
Sep 29 11:42:32.900 INF Extracted package name=content-textures2.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/9ba94e86704c5a6fca3f79c7077eae53 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/textures
Sep 29 11:42:32.966 INF Extracted package name=content-studio_svg_textures.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/f07b60093a555eb259986b65a526d52d dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/content/studio_svg_textures
Sep 29 11:42:33.477 INF Extracted package name=extracontent-luapackages.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/b2769609c7d8e0e80d491418e4f8278a dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/ExtraContent/LuaPackages
Sep 29 11:42:33.978 INF Extracted package name=RobloxStudio.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/124feceb20d6de3ce913a82088907541 dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7
Sep 29 11:42:34.180 INF Extracted package name=StudioFonts.zip path=/home/fernando/.var/app/org.vinegarhq.Vinegar/cache/vinegar/downloads/6df04925b4a61fdf50c06ff827eb369a dir=/home/fernando/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-1e5deb86743148f7/StudioFonts
Sep 29 11:42:34.181 ERR failed to setup roblox: install version-1e5deb86743148f7: setup: unhandled package: RibbonConfig.zip

### System information

```shell
Vinegar: v1.7.5 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.10.10-arch1-1
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1
```

**Comment by OverHash** [comment] 2024-09-29 10:20
Dupe of #435

**Comment by apprehensions** [comment] 2024-09-29 11:24
Duplicate of #435

**Closed by apprehensions** 2024-09-29 11:24 UTC
Labels: bug

**Comment by fernando433566** [comment] 2024-09-29 15:04
sorry for not reading properly
