### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#361] opened 2024-02-16 00:08 UTC
when running roblox studio this pops up
![image](https://github.com/vinegarhq/vinegar/assets/156553255/6bf25878-9625-4250-bf50-8b48d92bb02e)
Then I say oh just click it. It doesn't work. One day roblox studio is working and other its not... It did this once then stopped when 1.6.1 came out. I then update to 1.7.2 and it stops working again. Auth link doesn't work. Can't open studio

btw sorry 4 bugging u again.

**Comment by apprehensions** [comment] 2024-02-16 05:24
Duplicate of #32

**Closed by apprehensions** 2024-02-16 05:24 UTC
Labels: bug

**Comment by brotherman123** [comment] 2024-02-18 23:25
> Duplicate of #32

Might have found a solution. use command `flatpak run org.vinegarhq.Vinegar delete` to delete prefix.
