### ISSUE TITLE
When attempting to view submenus that require Wine-Gecko, FPS drops from 600 to 2 and nothing loads

### ISSUE THREAD

**Issue by RedrcknRbn** [vinegarhq/vinegar#146] opened 2023-09-07 23:33 UTC
Device Specifications:
Arch Linux
KDE Plasma 5
Xorg11
Nvidia GTX 1070
Intel(R) Core(TM) i9-9900K CPU
Two sticks of 8GB DDRM4

Submenus like Passes & Gear, Badges, Servers, etc drop the FPS down for a moment and don't load. Issue seems to be Wine-Gecko not working properly with Vinegar

https://github.com/vinegarhq/vinegar/assets/63996530/cdac5c92-c863-4e91-bfd4-f6a32ebbeaa3

**Comment by Thelolguy1** [comment] 2023-09-08 02:10
Duplicate of #32

**Closed by Thelolguy1** 2023-09-08 02:10 UTC
